name: Create A File
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - master

jobs:
  createFile:
    name: Create A File
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: 1arp/create-a-file-action@0.2
        with:
          path: 'pages'
          file: 'test.txt'
          content: |
            Hello
            World
